# Generated by Django 5.0.6 on 2024-05-15 16:54

import shopapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0011_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=shopapp.models.product_image_directory_path),
        ),
    ]
